### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by houruiyan** [pinellolab/pychromVAR#12]
I meet another problem, when I run another array. 
For this step, I do not know the reason.
![image](https://user-images.githubusercontent.com/56068158/225815189-89d9f51d-66a6-43f5-96fd-816ebf6fea63.png)

I also check my array. I did not find any nan or inf
![image](https://user-images.githubusercontent.com/56068158/225815358-e75f97fe-35c7-40cb-b775-4b4e83a1177e.png)

**Comment by houruiyan** [comment]
Could you help me? Thank you!

**Comment by lzj1769** [comment]
Hi, 

Can you check the gc_bias estimation to see if there are any NAN values?

**Comment by lzj1769** [comment]
@houruiyan 

Was the issue solved?

**Comment by houruiyan** [comment]
I forget it. Sorry. It seems that I did not fix it. But my supervisor tell me that we do not need to do it. So I give up.
